name: test
# https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test-vers:
    strategy:
      matrix:
        # Test with the latest supported release.
        node: ['12']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
